### ISSUE TITLE
Clicking up/down arrows does not lead to re-calculation

### ISSUE THREAD

**Issue by cweiske** [maximivanov/php-error-reporting-calculator#2]
The type of the number input field is "number", and the browsers show scroll buttons.
Clicking them does not re-calculate the flags, because you only listen to "keyup" and not "change" events.

**Comment by maximivanov** [comment]
Hey @cweiske good catch! Fixed that. I ended up using `input` event because `change` would not reflect changes as you type (only on focus leave). `input` handles keyboard events, number button clicks, copy/pasting.
Thanks for the heads up!
